const GOLDEN_CONFIG = {
  pr: 11,
  images: [
    {
      name: 'game_screen_midround_desktop',
      testImage: 'game_screen_midround_desktop_testImage.png',
      masterImage: 'game_screen_midround_desktop_masterImage.png',
      maskedDiff: 'game_screen_midround_desktop_maskedDiff.png',
      isolatedDiff: 'game_screen_midround_desktop_isolatedDiff.png',
    },
    {
      name: 'game_screen_midround_iphone_14_pro',
      testImage: 'game_screen_midround_iphone_14_pro_testImage.png',
      masterImage: 'game_screen_midround_iphone_14_pro_masterImage.png',
      maskedDiff: 'game_screen_midround_iphone_14_pro_maskedDiff.png',
      isolatedDiff: 'game_screen_midround_iphone_14_pro_isolatedDiff.png',
    },
    {
      name: 'game_screen_midround_iphone_se',
      testImage: 'game_screen_midround_iphone_se_testImage.png',
      masterImage: 'game_screen_midround_iphone_se_masterImage.png',
      maskedDiff: 'game_screen_midround_iphone_se_maskedDiff.png',
      isolatedDiff: 'game_screen_midround_iphone_se_isolatedDiff.png',
    },
    {
      name: 'home_screen_desktop',
      testImage: 'home_screen_desktop_testImage.png',
      masterImage: 'home_screen_desktop_masterImage.png',
      maskedDiff: 'home_screen_desktop_maskedDiff.png',
      isolatedDiff: 'home_screen_desktop_isolatedDiff.png',
    },
    {
      name: 'home_screen_iphone_14_pro',
      testImage: 'home_screen_iphone_14_pro_testImage.png',
      masterImage: 'home_screen_iphone_14_pro_masterImage.png',
      maskedDiff: 'home_screen_iphone_14_pro_maskedDiff.png',
      isolatedDiff: 'home_screen_iphone_14_pro_isolatedDiff.png',
    },
    {
      name: 'home_screen_iphone_se',
      testImage: 'home_screen_iphone_se_testImage.png',
      masterImage: 'home_screen_iphone_se_masterImage.png',
      maskedDiff: 'home_screen_iphone_se_maskedDiff.png',
      isolatedDiff: 'home_screen_iphone_se_isolatedDiff.png',
    },
    {
      name: 'lobby_screen_between_rounds_desktop',
      testImage: 'lobby_screen_between_rounds_desktop_testImage.png',
      masterImage: 'lobby_screen_between_rounds_desktop_masterImage.png',
      maskedDiff: 'lobby_screen_between_rounds_desktop_maskedDiff.png',
      isolatedDiff: 'lobby_screen_between_rounds_desktop_isolatedDiff.png',
    },
    {
      name: 'lobby_screen_between_rounds_iphone_14_pro',
      testImage: 'lobby_screen_between_rounds_iphone_14_pro_testImage.png',
      masterImage: 'lobby_screen_between_rounds_iphone_14_pro_masterImage.png',
      maskedDiff: 'lobby_screen_between_rounds_iphone_14_pro_maskedDiff.png',
      isolatedDiff: 'lobby_screen_between_rounds_iphone_14_pro_isolatedDiff.png',
    },
    {
      name: 'lobby_screen_between_rounds_iphone_se',
      testImage: 'lobby_screen_between_rounds_iphone_se_testImage.png',
      masterImage: 'lobby_screen_between_rounds_iphone_se_masterImage.png',
      maskedDiff: 'lobby_screen_between_rounds_iphone_se_maskedDiff.png',
      isolatedDiff: 'lobby_screen_between_rounds_iphone_se_isolatedDiff.png',
    },
    {
      name: 'lobby_screen_pregame_desktop',
      testImage: 'lobby_screen_pregame_desktop_testImage.png',
      masterImage: 'lobby_screen_pregame_desktop_masterImage.png',
      maskedDiff: 'lobby_screen_pregame_desktop_maskedDiff.png',
      isolatedDiff: 'lobby_screen_pregame_desktop_isolatedDiff.png',
    },
    {
      name: 'lobby_screen_pregame_iphone_14_pro',
      testImage: 'lobby_screen_pregame_iphone_14_pro_testImage.png',
      masterImage: 'lobby_screen_pregame_iphone_14_pro_masterImage.png',
      maskedDiff: 'lobby_screen_pregame_iphone_14_pro_maskedDiff.png',
      isolatedDiff: 'lobby_screen_pregame_iphone_14_pro_isolatedDiff.png',
    },
    {
      name: 'lobby_screen_pregame_iphone_se',
      testImage: 'lobby_screen_pregame_iphone_se_testImage.png',
      masterImage: 'lobby_screen_pregame_iphone_se_masterImage.png',
      maskedDiff: 'lobby_screen_pregame_iphone_se_maskedDiff.png',
      isolatedDiff: 'lobby_screen_pregame_iphone_se_isolatedDiff.png',
    },
    {
      name: 'pile_screen_desktop',
      testImage: 'pile_screen_desktop_testImage.png',
      masterImage: 'pile_screen_desktop_masterImage.png',
      maskedDiff: 'pile_screen_desktop_maskedDiff.png',
      isolatedDiff: 'pile_screen_desktop_isolatedDiff.png',
    },
    {
      name: 'pile_screen_iphone_14_pro',
      testImage: 'pile_screen_iphone_14_pro_testImage.png',
      masterImage: 'pile_screen_iphone_14_pro_masterImage.png',
      maskedDiff: 'pile_screen_iphone_14_pro_maskedDiff.png',
      isolatedDiff: 'pile_screen_iphone_14_pro_isolatedDiff.png',
    },
    {
      name: 'pile_screen_iphone_se',
      testImage: 'pile_screen_iphone_se_testImage.png',
      masterImage: 'pile_screen_iphone_se_masterImage.png',
      maskedDiff: 'pile_screen_iphone_se_maskedDiff.png',
      isolatedDiff: 'pile_screen_iphone_se_isolatedDiff.png',
    },
  ]
};
